<?php

$demo_data = array(
	array('id' => 1, 'cityName' => 'Amsterdam'),
	array('id' => 2, 'cityName' => 'Athens'),
	array('id' => 3, 'cityName' => 'Baghdad'),
	array('id' => 4, 'cityName' => 'Bangkok'),
	array('id' => 5, 'cityName' => 'Barcelona'),
	array('id' => 6, 'cityName' => 'Beijing'),
	array('id' => 7, 'cityName' => 'Belgrade'),
	array('id' => 8, 'cityName' => 'Berlin'),
	array('id' => 9, 'cityName' => 'Bogota'),
	array('id' => 10, 'cityName' => 'Bratislava'),
	array('id' => 11, 'cityName' => 'Brussels'),
	array('id' => 12, 'cityName' => 'Bucharest'),
	array('id' => 13, 'cityName' => 'Budapest'),
	array('id' => 14, 'cityName' => 'Buenos Aires'),
	array('id' => 15, 'cityName' => 'Cairo'),
	array('id' => 16, 'cityName' => 'CapeTown'),
	array('id' => 17, 'cityName' => 'Caracas'),
	array('id' => 18, 'cityName' => 'Chicago'),
	array('id' => 19, 'cityName' => 'Copenhagen'),
	array('id' => 20, 'cityName' => 'Dhaka'),
	array('id' => 21, 'cityName' => 'Dubai'),
	array('id' => 22, 'cityName' => 'Dublin'),
	array('id' => 23, 'cityName' => 'Frankfurt'),
	array('id' => 24, 'cityName' => 'Geneva'),
	array('id' => 25, 'cityName' => 'Hanoi'),
	array('id' => 26, 'cityName' => 'Helsinki'),
	array('id' => 27, 'cityName' => 'Hong Kong'),
	array('id' => 28, 'cityName' => 'Istanbul'),
	array('id' => 29, 'cityName' => 'Jakarta'),
	array('id' => 30, 'cityName' => 'Jerusalem'),
	array('id' => 31, 'cityName' => 'Johannesburg'),
	array('id' => 32, 'cityName' => 'Kabul'),
	array('id' => 33, 'cityName' => 'Karachi'),
	array('id' => 34, 'cityName' => 'Kiev'),
	array('id' => 35, 'cityName' => 'Kuala Lumpur'),
	array('id' => 36, 'cityName' => 'Lagos'),
	array('id' => 37, 'cityName' => 'Lahore'),
	array('id' => 38, 'cityName' => 'Lima'),
	array('id' => 39, 'cityName' => 'Lisbon'),
	array('id' => 40, 'cityName' => 'Ljubljana'),
	array('id' => 41, 'cityName' => 'London'),
	array('id' => 42, 'cityName' => 'Los Angeles'),
	array('id' => 43, 'cityName' => 'Luxembourg'),
	array('id' => 44, 'cityName' => 'Madrid'),
	array('id' => 45, 'cityName' => 'Manila'),
	array('id' => 46, 'cityName' => 'Marrakesh'),
	array('id' => 47, 'cityName' => 'Melbourne'),
	array('id' => 48, 'cityName' => 'Mexico City'),
	array('id' => 49, 'cityName' => 'Montreal'),
	array('id' => 50, 'cityName' => 'Moscow'),
	array('id' => 51, 'cityName' => 'Mumbai'),
	array('id' => 52, 'cityName' => 'Nairobi'),
	array('id' => 53, 'cityName' => 'New Delhi'),
	array('id' => 54, 'cityName' => 'New York'),
	array('id' => 55, 'cityName' => 'Nicosia'),
	array('id' => 56, 'cityName' => 'Oslo'),
	array('id' => 57, 'cityName' => 'Ottawa'),
	array('id' => 58, 'cityName' => 'Paris'),
	array('id' => 59, 'cityName' => 'Prague'),
	array('id' => 60, 'cityName' => 'Reykjavik'),
	array('id' => 61, 'cityName' => 'Riga'),
	array('id' => 62, 'cityName' => 'Rio de Janeiro'),
	array('id' => 63, 'cityName' => 'Rome'),
	array('id' => 64, 'cityName' => 'Saint Petersburg'),
	array('id' => 65, 'cityName' => 'San Francisco'),
	array('id' => 66, 'cityName' => 'Santiago de Chile'),
	array('id' => 67, 'cityName' => 'São Paulo'),
	array('id' => 68, 'cityName' => 'Seoul'),
	array('id' => 69, 'cityName' => 'Shanghai'),
	array('id' => 70, 'cityName' => 'Singapore'),
	array('id' => 71, 'cityName' => 'Sofia'),
	array('id' => 72, 'cityName' => 'Stockholm'),
	array('id' => 73, 'cityName' => 'Sydney'),
	array('id' => 74, 'cityName' => 'Tallinn'),
	array('id' => 75, 'cityName' => 'Tehran'),
	array('id' => 76, 'cityName' => 'The Hague'),
	array('id' => 77, 'cityName' => 'Tokyo'),
	array('id' => 78, 'cityName' => 'Toronto'),
	array('id' => 79, 'cityName' => 'Venice'),
	array('id' => 80, 'cityName' => 'Vienna'),
	array('id' => 81, 'cityName' => 'Vilnius'),
	array('id' => 82, 'cityName' => 'Warsaw'),
	array('id' => 83, 'cityName' => 'Washington D.C.'),
	array('id' => 84, 'cityName' => 'Wellington'),
	array('id' => 85, 'cityName' => 'Zagreb')
);

header("Content-Type: application/json; charset=utf-8");
echo json_encode(
	array_filter($demo_data, function($item) {
	    return strpos(strtolower($item['cityName']), strtolower($_GET['q'])) !== false;
	})
);


?>